### ISSUE TITLE
LibGuides Importer doesn't work for LibGuides 2 XML exports

### ISSUE THREAD

**Issue by sandbergja** [subjectsplus/SubjectsPlus#1183]
Additionally, I'm having trouble finding documentation on how the LibGuides 2 exports differ from the Libguides 1 exports.  I'd be happy to help with this, if I had some guidance from the community on the best approach for such a feature.

**Comment by agdarby** [comment]
Hi Jane, sorry we did the importer with version 1.  It was a bit of a one-off, and a semi-tremendous amount of work (with a significant amount of cleanup after).  We'd be happy to help out if we can, but since we're not LibGuides customers, we don't have access to the data that LG2 spits out.  If you are able to take the lead on this, drop me a line at agdarby@gmail.com and we'll see what we can do.

**Comment by agdarby** [comment]
Closing this because we won't be working on this issue.
