### ISSUE TITLE
Make SP compatible with PHP 7

### ISSUE THREAD

**Issue by agdarby** [subjectsplus/SubjectsPlus#1320]

**Comment by sandbergja** [comment]
Just a note that I get deprecation warnings for this function in PHP 7.4.6: `get_magic_quotes_gpc`

Magic quotes have not been available since PHP 5.3 (the oldest version of PHP supported by SubjectsPlus).  Maybe we could get rid of those `get_magic_quotes_gpc` checks and bump the minimum version to PHP 5.4?

**Comment by sandbergja** [comment]
Another deprecation warning in 7.4.6:

Deprecated: implode(): Passing glue string after array is deprecated. Swap the parameters in /var/www/html/lib/SubjectsPlus/Control/Guide.php on line 1043

**Comment by rxd702** [comment]
Merged pull requests handling deprecation warnings for `get_magic_quotes_gpc` and `implode`.
However, still a work in progress.

`get_magic_quotes_gpc` https://github.com/subjectsplus/SubjectsPlus/pull/1477
`implode` https://github.com/subjectsplus/SubjectsPlus/pull/1474
