### ISSUE TITLE
$page_title = _("Search Results");

### ISSUE THREAD

**Issue by louisachoy** [subjectsplus/SubjectsPlus#148]
Hello!

I'm not sure if it's just my hosting environment, but I notice that my control/sp/search.php page won't load if Line 3 is formatted as "$page_title = _("Search Results");".  It is only after I compare the $page_title line in other sp pages and removed the underscore and parentheses from Search Results (so it's $page_title = "Search Results";) that the page would load.

**Comment by agdarby** [comment]
We need to investigate this.  Ideally, all strings should be run through the internationalization function _("text to be translated") , but maybe it's being declared too early in that file (i.e., before function.php is pulled in)

**Comment by agdarby** [comment]
Ah, okay, it's because you don't have gettext extension installed on your server (just turned off on localhost and see what you're talking about).  It's a bit of a quandary, because the header file pulls in the function file (with the internationalization fallback function), but you need to set the page_title before the header file is called (or else it's too late to render the page title).

**Comment by agdarby** [comment]
just moved this down the source code a bit, so gettext check had already happened
