### ISSUE TITLE
security question re: files & directories writable by php

### ISSUE THREAD

**Issue by kenirwin** [subjectsplus/SubjectsPlus#287]
Hi folks,
The installation guide for v.3 (http://subjectsplus.com/wiki2/index.php?title=Installation/Upgrade_3.0) requires that several files and directories be writable by the webserver. Having so many files including htaccess files writable by PHP makes me concerned about the security implications. Can you comment on that at all? I'm anticipating that my sysadmin will be concerned. 

Do the files need to stay writable, or can they be locked down after installation? Why do the htaccess files need to be writable? Is there a hand-editing opportunity that could evade that necessity?

Thanks
Ken

**Comment by little9** [comment]
Ken, 

When we write documentation for the next version (or before) we'll going to revise these instructions. On our Google Group I just replied to someone who had a similar question about these files:

 Since SubjectsPlus can run on multiple servers (Apache,IIS,Nginx) this can get complicated (Apache can be run as different users, using permissions that are too open will make the file insecure, etc.). 

This answer at the Ubuntu Q&A site provides a lot of information about how to make those files writable:

https://askubuntu.com/questions/58725/how-do-we-know-that-a-directory-is-apache-writable

It includes information about how to find out what user your instance of Apache is running under (this varies depending on the distro or the way that Apache has been set up) and the best way to setup the permissions. 

After the installation you could lock down the .htaccess files if you want to edit them directly. I believe there is some functionality in the administrative settings that alters the .htaccess files (@agdarby would probably know more about this).
