### ISSUE TITLE
Impossible to scroll to top of boxes in guide using a trackpad (maybe scroll wheel as well) 

### ISSUE THREAD

**Issue by little9** [subjectsplus/SubjectsPlus#311]
When I scroll to the top of the list of boxes it bounces back to the second row of boxes and I have to click on the scroll bar to move it to the top:

![fzx97fzahp](https://cloud.githubusercontent.com/assets/4324761/11100059/e3abe6ac-887c-11e5-99ed-f6dc5283785d.gif)

**Comment by cgb37** [comment]
the scrollbar bounce only seems to occur on mac osx using chrome. the scrollIncrement property of enscroll.js can be set to 1 which minimizes the bounce but it makes the scroll wheel super slow. So maybe because it only seems to affect a small percentage of users we leave it as is.


see: https://github.com/jstoudt/enscroll/issues/61
