### ISSUE TITLE
Allow reordering of Subject Specialists

### ISSUE THREAD

**Issue by agdarby** [subjectsplus/SubjectsPlus#645]
when you have more than one, so it's not just alphabetical

**Comment by agdarby** [comment]
3

**Comment by abelfacenda** [comment]
[b2b8d6b964f3f58aae56d24a817c4f3ca0315a45] 
-Added sortableGuideStaff JS file to allow reordering of the subject specialists in the guides metadata page.
-Added column staff_guide_order to staff_subject table to store order of subject specialists
-Changed SQL query to ORDER BY the column staff_guide_order instead of last name.
-Updated Installer.php and Updated.php to handle the new column.
